name: vello
description: Vello Passageiro

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.6
  
  # Firebase (versões atualizadas)
  firebase_core: ^3.15.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.1.3
  
  # Notificações
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Provider (ADICIONADO)
  provider: ^6.1.2
  
  # Outras dependências
  image_picker: ^1.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/

